/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View;

import javax.swing.table.TableModel;

/**
 *
 * @author garroakion
 */
public class favoritos extends javax.swing.JPanel {

    /**
     * Creates new form favoritos
     */
    public favoritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };};

            setBackground(new java.awt.Color(255, 255, 255));
            setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            tableInfo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tableInfo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tableInfoMouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(tableInfo);

            add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 700));
        }// </editor-fold>//GEN-END:initComponents

    private void tableInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInfoMouseClicked
          ProductInformation pi = new ProductInformation();
        pi.setVisible(true);
        pi.pack();

        int selectedRow = tableInfo.getSelectedRow();
        TableModel tm = tableInfo.getModel();

        String idbuysale = tm.getValueAt(selectedRow, 0).toString();
        String datepost = tm.getValueAt(selectedRow, 1).toString();
        String username = tm.getValueAt(selectedRow, 2).toString();
        String nametype = tm.getValueAt(selectedRow, 3).toString();
        String namebrand = tm.getValueAt(selectedRow, 4).toString();
        String namemodel = tm.getValueAt(selectedRow, 5).toString();
        String namecondition = tm.getValueAt(selectedRow, 6).toString();
        String manufacturedate = tm.getValueAt(selectedRow, 7).toString();
        String descriptionclock = tm.getValueAt(selectedRow, 8).toString();
        String price = tm.getValueAt(selectedRow, 9).toString();

        // ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 5);
        pi.productInfoId.setText(idbuysale);
        pi.productInfoPosted.setText(datepost);
        pi.productInfoBy.setText(username);
        pi.productInfoType.setText(nametype);
        pi.productInfoBrandClock.setText(namebrand);
        pi.productInfoModel.setText(namemodel);
        pi.productInfoCondition.setText(namecondition);
        pi.productInfoManufactureDate.setText(manufacturedate);
        pi.productInfoDescription.setText(descriptionclock);
        pi.productInfoPrice.setText(price);
    }//GEN-LAST:event_tableInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
