/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View;

import com.Controllers.Controller_Brand;
import com.Controllers.Controller_BuySale;
import com.Controllers.Controller_Main;
import com.Controllers.Controller_ModelP;
import com.Controllers.Controller_TypeClock;
import com.Controllers.Controller_Condition;
import com.Controllers.Controller_BuyStatus;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.TableModel;

        

/**
 *
 * @author garroakion
 */
public class insertarRelojes extends javax.swing.JPanel {

    private Controller_Main mainCont = Controller_Main.getContMain();
    private Controller_Brand controllerB;
    private Controller_ModelP controllerModelP;
    private Controller_TypeClock controllerType;
    private Controller_Condition controllerCondition;
    private Controller_BuyStatus controllerBuyStatus;
    private Controller_BuySale controllerBuySale;
    
    /**
     * Creates new form insertarRelojes
     */
    public insertarRelojes() {
        initComponents();
        controllerB = mainCont.getContBrand();
        controllerModelP = mainCont.getContModelP();
        controllerType = mainCont.getContTypeClock();
        controllerCondition = mainCont.getContCondition();
        controllerBuyStatus = mainCont.getContBuyStatus();
        controllerBuySale = mainCont.getContBuySale();
        this.manufactureDate.setLocale(Locale.ENGLISH);

        fillBrand();
        fillModel();

        fillCondition();
        fillBuyStatus();
        fillTable();

    }

    private void fillBrand() {
        try {
            ArrayList<String> listC = controllerB.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboBrand.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillModel() {
        try {
            ArrayList<String> listC = controllerModelP.listInfoCombo(comboBrand.getSelectedItem().toString());
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboModel.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillCondition() {
        try {
            ArrayList<String> listC = controllerCondition.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboCond.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillBuyStatus() {
        try {
            ArrayList<String> listC = controllerBuyStatus.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboBuyStatus.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillTable() {
        try {
            this.tableInfo.setModel(controllerBuySale.listMyClocks(mainCont.getUsername()));
            this.tableInfo.revalidate();
            this.tableInfo.repaint();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBuyStatus = new javax.swing.JComboBox<>();
        comboBrand = new javax.swing.JComboBox<>();
        comboModel = new javax.swing.JComboBox<>();
        comboCond = new javax.swing.JComboBox<>();
        priceField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };};
            manufactureDate = new com.toedter.calendar.JDateChooser();
            jLabel14 = new javax.swing.JLabel();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            newPrice = new javax.swing.JTextField();

            setBackground(new java.awt.Color(255, 255, 255));
            setPreferredSize(new java.awt.Dimension(730, 700));
            setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel6.setText("Brand:");
            add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

            jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel7.setText("Buy Status:");
            add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, 30));

            jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel8.setText("Model:");
            add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 80, 30));

            jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel10.setText("Condition:");
            add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 100, 30));

            jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel11.setText("Manufacture Date");
            add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 30));

            jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel12.setText("Price:");
            add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 30));

            comboBuyStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
            comboBuyStatus.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comboBuyStatusActionPerformed(evt);
                }
            });
            add(comboBuyStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 140, -1));

            comboBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            comboBrand.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    comboBrandItemStateChanged(evt);
                }
            });
            add(comboBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 140, -1));

            comboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 140, -1));

            comboCond.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboCond, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 140, -1));

            priceField.setColumns(10);
            add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 140, -1));

            descriptionField.setColumns(100);
            descriptionField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    descriptionFieldActionPerformed(evt);
                }
            });
            add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 240, 30));

            jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel13.setText("Vintage:");
            add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 30));

            jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
            jComboBox6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox6ActionPerformed(evt);
                }
            });
            add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));

            jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jButton1.setText("Add new clock");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 40));

            tableInfo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tableInfo.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tableInfoMouseClicked(evt);
                }
            });
            jScrollPane2.setViewportView(tableInfo);

            add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 730, 430));
            add(manufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

            jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel14.setText("Description:");
            add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, 30));

            jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jButton2.setText("Change Status");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 170, 40));

            jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jButton3.setText("Change  Price");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 170, 40));
            add(newPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 40));
        }// </editor-fold>//GEN-END:initComponents

    private void comboBuyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuyStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuyStatusActionPerformed

    private void descriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionFieldActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void comboBrandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBrandItemStateChanged
        fillModel();

    }//GEN-LAST:event_comboBrandItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.util.Date utilDate = this.manufactureDate.getDate();
            java.sql.Date manufactureDate = new java.sql.Date(utilDate.getTime());
            mainCont.createWindowMessage(this.controllerBuySale.create(
                    this.comboModel.getSelectedItem().toString(),
                    this.comboCond.getSelectedItem().toString(),
                    this.descriptionField.getText(),
                    manufactureDate,
                    "",
                    Integer.parseInt(this.priceField.getText()),
                    mainCont.getUsername(),
                    this.comboBuyStatus.getSelectedItem().toString(),
                    this.comboBrand.getSelectedItem().toString()
            ), "Creating Clock");

            fillTable();

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInfoMouseClicked
      if (evt.getClickCount() == 2 && tableInfo.getSelectedRow() != -1) {
        ProductInformation pi = new ProductInformation();
        pi.setVisible(true);
        pi.pack();

        int selectedRow = tableInfo.getSelectedRow();
        TableModel tm = tableInfo.getModel();

        String idbuysale = tm.getValueAt(selectedRow, 0).toString();
        String nametype = tm.getValueAt(selectedRow, 1).toString();
        String namebrand = tm.getValueAt(selectedRow, 2).toString();
        String namemodel = tm.getValueAt(selectedRow, 3).toString();
         String namecondition = tm.getValueAt(selectedRow, 4).toString();
         String manufacturedate = tm.getValueAt(selectedRow, 5).toString();
        String descriptionclock = tm.getValueAt(selectedRow, 6).toString();
        String price = tm.getValueAt(selectedRow, 7).toString();
        
        String datepost = tm.getValueAt(selectedRow, 8).toString();
        //String username = tm.getValueAt(selectedRow, 2).toString();

       
        
        
        
        pi.productInfoBrand6.setText("Buy Status");
        pi.productInfoBrand7.setText("");
        // ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 5);
        pi.productInfoId.setText(idbuysale);
        pi.productInfoPosted.setText(datepost);
        //pi.productInfoBy.setText(username);
        pi.productInfoType.setText(nametype);
        pi.productInfoBrandClock.setText(namebrand);
        pi.productInfoModel.setText(namemodel);
        pi.productInfoCondition.setText(namecondition);
        pi.productInfoManufactureDate.setText(manufacturedate);
        pi.productInfoDescription.setText(descriptionclock);
        pi.productInfoPrice.setText(price);    
        } 
    }//GEN-LAST:event_tableInfoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                 try {
            if (this.tableInfo.getSelectedRow() != -1) {
                mainCont.createWindowMessage(this.controllerBuySale.updateStatus(this.tableInfo.getValueAt(tableInfo.getSelectedRow(), 0).toString(), this.comboBuyStatus.getSelectedItem().toString()), "Change Status ");
                fillTable();
                

            } else {
                mainCont.createWindowMessage("Select a clock", "No post Selected");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                       try {
            if (this.tableInfo.getSelectedRow() != -1 && CheckFields.onlyCheckNumbers(this.newPrice.getText())) {
                mainCont.createWindowMessage(this.controllerBuySale.updatePrice(this.tableInfo.getValueAt(tableInfo.getSelectedRow(), 0).toString(), Integer.parseInt( this.newPrice.getText().toString())), "Change Price ");
                fillTable();
                

            } else {
                mainCont.createWindowMessage("Clock not selected or not a valid price", "This is not a valid price");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBrand;
    private javax.swing.JComboBox<String> comboBuyStatus;
    private javax.swing.JComboBox<String> comboCond;
    private javax.swing.JComboBox<String> comboModel;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser manufactureDate;
    private javax.swing.JTextField newPrice;
    private javax.swing.JTextField priceField;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
