/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View;

import com.Controllers.Controller_Brand;
import com.Controllers.Controller_Main;
import com.Controllers.Controller_ModelP;
import com.Controllers.Controller_TypeClock;
import com.Controllers.Controller_Condition;
import com.Controllers.Controller_BuyStatus;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author garroakion
 */
public class insertarRelojes extends javax.swing.JPanel {

    private Controller_Main mainCont = Controller_Main.getContMain();
    private Controller_Brand controllerB;
    private Controller_ModelP controllerModelP;
    private Controller_TypeClock controllerType;
    private Controller_Condition controllerCondition;
    private Controller_BuyStatus controllerBuyStatus;

    /**
     * Creates new form insertarRelojes
     */
    public insertarRelojes() {
        initComponents();
        controllerB = mainCont.getContBrand();
        controllerModelP = mainCont.getContModelP();
        controllerType = mainCont.getContTypeClock();
        controllerCondition = mainCont.getContCondition();
        controllerBuyStatus = mainCont.getContBuyStatus();
        
        fillBrand();
        fillModel();
        fillType();
        fillCondition();
        
        

    }

    private void fillBrand() {
        try {
            ArrayList<String> listC = controllerB.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboBrand.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }
    

    private void fillModel() {
        try {
            ArrayList<String> listC = controllerModelP.listInfoCombo(comboBrand.getSelectedItem().toString());
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboModel.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillType() {
        try {
            ArrayList<String> listC = controllerType.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboType.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillCondition() {
        try {
            ArrayList<String> listC = controllerCondition.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboCond.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBuyStatus = new javax.swing.JComboBox<>();
        comboBrand = new javax.swing.JComboBox<>();
        comboModel = new javax.swing.JComboBox<>();
        comboCond = new javax.swing.JComboBox<>();
        comboType = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };};

            setBackground(new java.awt.Color(255, 255, 255));
            setPreferredSize(new java.awt.Dimension(730, 700));
            setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(0, 0, 0));
            jLabel6.setText("Brand:");
            add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

            jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(0, 0, 0));
            jLabel7.setText("Buy Status:");
            add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, 30));

            jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(0, 0, 0));
            jLabel8.setText("Model:");
            add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 80, 30));

            jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(0, 0, 0));
            jLabel9.setText("Type:");
            add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

            jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(0, 0, 0));
            jLabel10.setText("Condition:");
            add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 100, 30));

            jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(0, 0, 0));
            jLabel11.setText("Description:");
            add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 30));

            jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(0, 0, 0));
            jLabel12.setText("Price:");
            add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 30));

            comboBuyStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
            comboBuyStatus.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comboBuyStatusActionPerformed(evt);
                }
            });
            add(comboBuyStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 140, -1));

            comboBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            comboBrand.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    comboBrandItemStateChanged(evt);
                }
            });
            add(comboBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 140, -1));

            comboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 140, -1));

            comboCond.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboCond, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 140, -1));

            comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, -1));
            add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 140, -1));

            jTextField2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField2ActionPerformed(evt);
                }
            });
            add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

            jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(0, 0, 0));
            jLabel13.setText("Vintage:");
            add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, 30));

            jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
            jComboBox6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox6ActionPerformed(evt);
                }
            });
            add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));

            jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
            jButton1.setText("Add new clock");
            add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 160, 70));

            tableInfo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane2.setViewportView(tableInfo);

            add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 730, 430));
        }// </editor-fold>//GEN-END:initComponents

    private void comboBuyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuyStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuyStatusActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void comboBrandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBrandItemStateChanged
        fillModel();
        
    }//GEN-LAST:event_comboBrandItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBrand;
    private javax.swing.JComboBox<String> comboBuyStatus;
    private javax.swing.JComboBox<String> comboCond;
    private javax.swing.JComboBox<String> comboModel;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
