/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.View;

import com.Controllers.Controller_Main;
import com.Controllers.Controller_Shcart_appuserxclock;
import java.awt.Color;

/**
 *
 * @author garroakion
 */
public class ProductInformation extends javax.swing.JFrame {

    /**
     * Creates new form ProductInformation
     */
     private Controller_Main mainCont = Controller_Main.getContMain();
      private Controller_Shcart_appuserxclock controllerShCart;
    public ProductInformation() {
        initComponents();
        controllerShCart = mainCont.getContShCart();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        productPhoto = new javax.swing.JLabel();
        productInfoBrand = new javax.swing.JLabel();
        productInfoBrand1 = new javax.swing.JLabel();
        productInfoBrand2 = new javax.swing.JLabel();
        productInfoBrand3 = new javax.swing.JLabel();
        addToCart = new javax.swing.JButton();
        productInfoId = new javax.swing.JLabel();
        productInfoType = new javax.swing.JLabel();
        productInfoCondition = new javax.swing.JLabel();
        productInfoPrice = new javax.swing.JLabel();
        productInfoBrand6 = new javax.swing.JLabel();
        productInfoPosted = new javax.swing.JLabel();
        productInfoBrand7 = new javax.swing.JLabel();
        productInfoBy = new javax.swing.JLabel();
        productInfoBrand8 = new javax.swing.JLabel();
        productInfoBrandClock = new javax.swing.JLabel();
        productInfoBrand9 = new javax.swing.JLabel();
        productInfoModel = new javax.swing.JLabel();
        productInfoBrand10 = new javax.swing.JLabel();
        productInfoManufactureDate = new javax.swing.JLabel();
        productInfoBrand11 = new javax.swing.JLabel();
        productInfoDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(62, 114, 179));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 72));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Information");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 14, 455, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 51, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productPhoto.setBackground(new java.awt.Color(255, 255, 255));
        productPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 64)));
        jPanel4.add(productPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 250, 270));

        productInfoBrand.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand.setText("Id:");
        jPanel4.add(productInfoBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 19));

        productInfoBrand1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand1.setText("Condition:");
        jPanel4.add(productInfoBrand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 130, -1));

        productInfoBrand2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand2.setText("Price:");
        jPanel4.add(productInfoBrand2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 110, -1));

        productInfoBrand3.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand3.setText("Type:");
        jPanel4.add(productInfoBrand3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, -1));

        addToCart.setBackground(new java.awt.Color(0, 77, 64));
        addToCart.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        addToCart.setForeground(new java.awt.Color(255, 255, 255));
        addToCart.setText("Add to cart");
        addToCart.setBorder(null);
        addToCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        jPanel4.add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 169, 50));

        productInfoId.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, 20));

        productInfoType.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 170, 20));

        productInfoCondition.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 20));

        productInfoPrice.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 170, 20));

        productInfoBrand6.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand6.setText("Posted:");
        jPanel4.add(productInfoBrand6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 19));

        productInfoPosted.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoPosted, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 170, 20));

        productInfoBrand7.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand7.setText("By:");
        jPanel4.add(productInfoBrand7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 90, 19));

        productInfoBy.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 20));

        productInfoBrand8.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand8.setText("Brand:");
        jPanel4.add(productInfoBrand8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, 19));

        productInfoBrandClock.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoBrandClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 20));

        productInfoBrand9.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand9.setText("Model:");
        jPanel4.add(productInfoBrand9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, 19));

        productInfoModel.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 170, 20));

        productInfoBrand10.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand10.setText("Manufacture Date:");
        jPanel4.add(productInfoBrand10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, -1));

        productInfoManufactureDate.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoManufactureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 20));

        productInfoBrand11.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        productInfoBrand11.setText("Description:");
        jPanel4.add(productInfoBrand11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 150, -1));

        productInfoDescription.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        jPanel4.add(productInfoDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 380, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1130, 640));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
            try {
            if (!this.productInfoId.equals("")) {
                mainCont.createWindowMessage(this.controllerShCart.create(mainCont.getUsername(), this.productInfoId.getText()), "Clock Added to Shopping Cart");

            } else {
                mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_addToCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel productInfoBrand;
    private javax.swing.JLabel productInfoBrand1;
    private javax.swing.JLabel productInfoBrand10;
    private javax.swing.JLabel productInfoBrand11;
    private javax.swing.JLabel productInfoBrand2;
    private javax.swing.JLabel productInfoBrand3;
    public javax.swing.JLabel productInfoBrand6;
    public javax.swing.JLabel productInfoBrand7;
    private javax.swing.JLabel productInfoBrand8;
    private javax.swing.JLabel productInfoBrand9;
    public javax.swing.JLabel productInfoBrandClock;
    public javax.swing.JLabel productInfoBy;
    public javax.swing.JLabel productInfoCondition;
    public javax.swing.JLabel productInfoDescription;
    public javax.swing.JLabel productInfoId;
    public javax.swing.JLabel productInfoManufactureDate;
    public javax.swing.JLabel productInfoModel;
    public javax.swing.JLabel productInfoPosted;
    public javax.swing.JLabel productInfoPrice;
    public javax.swing.JLabel productInfoType;
    public javax.swing.JLabel productPhoto;
    // End of variables declaration//GEN-END:variables
}
