COMMENT ON COLUMN APPUSER.IDAPPUSER
IS 'IDENTIFIER OF APPUSER';

COMMENT ON COLUMN APPUSER.IDPEOPLE
IS 'Reference to the person';



COMMENT ON COLUMN BUYERRATING.IDAPPUSER
IS 'Reference to the user';


COMMENT ON COLUMN CONDITION.NAMECONDITION
IS 'Name of the condition';

COMMENT ON COLUMN MODELP.IDTYPECLOCK
IS 'Reference to the type of clock';


COMMENT ON COLUMN PEOPLE.IDENTIFICATIONNUMBER
IS 'id of the person';

COMMENT ON COLUMN PEOPLE.IDENFITIFCATIONTYPE
IS 'Reference to type of id';

COMMENT ON COLUMN PEOPLE.gender
IS 'Reference to gender ';
Comment creado.


