/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View.adminPanels;

import com.Controllers.Controller_City;
import com.Controllers.Controller_Country;
import com.Controllers.Controller_District;
import com.Controllers.Controller_Main;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author garroakion
 */
public class Address extends javax.swing.JPanel {

    private  Controller_Main mainCont= Controller_Main.getContMain();
    private  Controller_Country controllerCountry;
    private  Controller_City controllerCity;
    private  Controller_District controllerDistrict;

    /**
     * Creates new form District
     */
    public Address() {
        initComponents();
        controllerCountry=mainCont.getContCountry();
        controllerCity=mainCont.getContCity();
        controllerDistrict=mainCont.getContDistrict();
        this.fillCountry();
    }

    

    
        private void fillCity(){
    try{
           this.comboCityF.removeAllItems();
            int number=this.comboCountry.getSelectedIndex();
            ArrayList<String>listCity= new ArrayList<String>();
            listCity= controllerCity.listInfo(this.comboCountry.getItemAt(number));
            DefaultComboBoxModel modelList= new DefaultComboBoxModel(listCity.toArray());

            this.comboCityF.setModel(modelList);

           System.out.println(listCity.size());
            //this.comboCity.setModel(new DefaultComboBoxModel(arr));

            this.fillDistrict();
            
        }catch(Exception e){
        System.out.println("Error in fillcity  "+e.toString());
        }

    
    }
        

        
    private void fillCountry(){
        try{
            ArrayList<String> listC= controllerCountry.listInfoCombo();
            DefaultComboBoxModel listF=new DefaultComboBoxModel(listC.toArray());
            this.comboCountry.setModel(listF);
            this.fillCity();
            
        }catch(Exception e){
        System.out.println(e.toString());
        }
    
    }
    
    
    
    private void fillDistrict(){
        try{
            ArrayList<String> listC= controllerDistrict.listInfo(this.comboCityF.getSelectedItem().toString(),this.comboCountry.getSelectedItem().toString());
            DefaultComboBoxModel listF=new DefaultComboBoxModel(listC.toArray());
            this.comboDistrict.setModel(listF);
            
        }catch(Exception e){
        
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboDistrict = new javax.swing.JComboBox<>();
        comboCityF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createButton1 = new javax.swing.JButton();
        createButton2 = new javax.swing.JButton();
        createButton3 = new javax.swing.JButton();
        nameTextField2 = new javax.swing.JTextField();
        countryCodeField = new javax.swing.JTextField();
        modifyButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("City:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCountryItemStateChanged(evt);
            }
        });
        add(comboCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cod:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 30));

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create District");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 120, 30));

        modifyButton.setBackground(new java.awt.Color(0, 0, 0));
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Delete Country");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 130, 30));

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableInfo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 730, 460));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Country:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        comboDistrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboDistrict, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 300, 30));

        comboCityF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCityF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCityFItemStateChanged(evt);
            }
        });
        add(comboCityF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 300, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("District Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Agregar:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        createButton1.setBackground(new java.awt.Color(0, 0, 0));
        createButton1.setForeground(new java.awt.Color(255, 255, 255));
        createButton1.setText("Create");
        createButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton1ActionPerformed(evt);
            }
        });
        add(createButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, 30));

        createButton2.setBackground(new java.awt.Color(0, 0, 0));
        createButton2.setForeground(new java.awt.Color(255, 255, 255));
        createButton2.setText("Create Country");
        createButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton2ActionPerformed(evt);
            }
        });
        add(createButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, 30));

        createButton3.setBackground(new java.awt.Color(0, 0, 0));
        createButton3.setForeground(new java.awt.Color(255, 255, 255));
        createButton3.setText("Create City");
        createButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton3ActionPerformed(evt);
            }
        });
        add(createButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, 30));

        nameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField2ActionPerformed(evt);
            }
        });
        add(nameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));
        add(countryCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, -1));

        modifyButton1.setBackground(new java.awt.Color(0, 0, 0));
        modifyButton1.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton1.setText("Modify");
        add(modifyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    

    private void createButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton2ActionPerformed
               try{
            if (!this.nameTextField2.getText().isBlank() && !this.countryCodeField.getText().isBlank()){
                mainCont.createWindowMessage(controllerCountry.create(this.nameTextField2.getText(),this.countryCodeField.getText()), "Create Country");
                fillCountry();

            }
            else {mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_createButton2ActionPerformed

    private void createButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton3ActionPerformed
               try{
            if (!this.nameTextField2.getText().isBlank() && this.comboCountry.getSelectedItem().toString()!=null){
                mainCont.createWindowMessage(controllerCity.create(this.nameTextField2.getText(),this.comboCountry.getSelectedItem().toString()), "Create City");
                fillCity();

            }
            else {mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }        // TODO add your handling code here:
                        // TODO add your handling code here:
    }//GEN-LAST:event_createButton3ActionPerformed

    private void createButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButton1ActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
                try{
            if (!this.nameTextField2.getText().isBlank() && this.comboCountry.getSelectedItem().toString()!=null && this.comboCityF.getSelectedItem().toString()!=null){
                mainCont.createWindowMessage(controllerDistrict.create(this.nameTextField2.getText(),this.comboCityF.getSelectedItem().toString(),this.comboCountry.getSelectedItem().toString()), "Create District");
                fillDistrict();

            }
            else {mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }        
                  
    }//GEN-LAST:event_createButtonActionPerformed

    private void comboCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCountryItemStateChanged
        try{
         this.fillCity();
         this.fillDistrict();
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_comboCountryItemStateChanged

    private void comboCityFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCityFItemStateChanged
       this.fillDistrict();
    }//GEN-LAST:event_comboCityFItemStateChanged

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
                      try{
            if (comboCountry.getSelectedIndex()!=-1){
                mainCont.createWindowMessage(this.controllerCountry.deleteT(this.comboCountry.getSelectedItem().toString()), "Deleting Country");
                fillCountry();

            }
            else {mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }        
            
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void nameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCityF;
    private javax.swing.JComboBox<String> comboCountry;
    private javax.swing.JComboBox<String> comboDistrict;
    private javax.swing.JTextField countryCodeField;
    private javax.swing.JButton createButton;
    private javax.swing.JButton createButton1;
    private javax.swing.JButton createButton2;
    private javax.swing.JButton createButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton modifyButton1;
    private javax.swing.JTextField nameTextField2;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
