/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View.adminPanels;

import com.Controllers.Controller_AppuserxPeople;
import com.Controllers.Controller_Gender;
import com.Controllers.Controller_Main;
import com.Controllers.Controller_UserType;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author garroakion
 */
public class ChangeUserType extends javax.swing.JPanel {

    private Controller_Main mainCont = Controller_Main.getContMain();
    private Controller_AppuserxPeople controller;
    private Controller_UserType controllerType;
    


    public ChangeUserType() {
        initComponents();
        controller=mainCont.getContAppUserPeople();
        controllerType=mainCont.getContUserType();
        fillTable();
        fillComboType();
    }
    
        private void fillTable(){
        try{
        this.tableInfo.setModel(controller.listInfoTableType());
        this.tableInfo.revalidate();
        this.tableInfo.repaint();
        }catch(Exception e){
            System.out.println(e.toString());
        }
    }
        
        
       private void fillComboType(){
       
        try {
            ArrayList<String> listC = controllerType.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboType.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }
       
       
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {
                return false;
            };};
            changeButton = new javax.swing.JButton();
            comboType = new javax.swing.JComboBox<>();

            setBackground(new java.awt.Color(255, 255, 255));
            setPreferredSize(new java.awt.Dimension(730, 660));
            setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
            jLabel3.setText("Type:");
            add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 40));

            tableInfo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane2.setViewportView(tableInfo);

            add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 730, 510));

            changeButton.setBackground(new java.awt.Color(0, 0, 0));
            changeButton.setForeground(new java.awt.Color(255, 255, 255));
            changeButton.setText("Change");
            changeButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    changeButtonActionPerformed(evt);
                }
            });
            add(changeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 80, 30));

            comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 30));
        }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed

                      try{
            if (tableInfo.getSelectedRow()!=-1){
               mainCont.createWindowMessage(this.controller.updateUserType(this.tableInfo.getValueAt(tableInfo.getSelectedRow(), 0).toString(),this.comboType.getSelectedItem().toString()), "Updating Type");
                fillTable();

            }
            else {mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        }
        catch(Exception e){
            System.out.println(e.toString());
        }        
              }//GEN-LAST:event_changeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
