/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View.adminPanels;

import com.Controllers.Controller_Brand;
import com.Controllers.Controller_Main;
import com.Controllers.Controller_ModelP;
import com.Controllers.Controller_TypeClock;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author garroakion
 */
public class Model extends javax.swing.JPanel {

    private Controller_Main mainCont = Controller_Main.getContMain();
    private Controller_Brand controllerB;

    private Controller_ModelP controllerModelP;
    private Controller_TypeClock controllerType;

    /**
     * Creates new form Model
     */
    public Model() {
        initComponents();
        controllerB = mainCont.getContBrand();
        controllerModelP = mainCont.getContModelP();

        controllerType = mainCont.getContTypeClock();
        fillType();
        fillBrand();
        fillModel();

    }

    private void fillBrand() {
        try {
            ArrayList<String> listC = controllerB.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboBrand.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillModel() {
        try {

            ArrayList<String> listC = controllerModelP.listInfoCombo(this.comboBrand.getSelectedItem().toString());
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboModel.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void fillType() {
        try {
            ArrayList<String> listC = controllerType.listInfoCombo();
            DefaultComboBoxModel listF = new DefaultComboBoxModel(listC.toArray());
            this.comboType.setModel(listF);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        createButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboModel = new javax.swing.JComboBox<>();
        comboBrand = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        createButton2 = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        createButton1 = new javax.swing.JButton();
        deleteModelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(730, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Brand:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableInfo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 730, 500));

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create Model");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 40));

        comboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 300, 30));

        comboBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBrand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBrandItemStateChanged(evt);
            }
        });
        add(comboBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Model name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 50));

        createButton2.setBackground(new java.awt.Color(0, 0, 0));
        createButton2.setForeground(new java.awt.Color(255, 255, 255));
        createButton2.setText("Create Brand");
        createButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton2ActionPerformed(evt);
            }
        });
        add(createButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 130, 30));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 140, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 50));

        createButton1.setBackground(new java.awt.Color(0, 0, 0));
        createButton1.setForeground(new java.awt.Color(255, 255, 255));
        createButton1.setText("Delete Brand");
        createButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton1ActionPerformed(evt);
            }
        });
        add(createButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, 30));

        deleteModelButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteModelButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteModelButton.setText("Delete Model");
        deleteModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteModelButtonActionPerformed(evt);
            }
        });
        add(deleteModelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        try {
            if (!this.nameField.getText().isBlank() && this.comboBrand.getSelectedItem().toString() != null && this.comboType.getSelectedIndex() != -1) {
                mainCont.createWindowMessage(controllerModelP.create(this.nameField.getText(), this.comboBrand.getSelectedItem().toString(), this.comboType.getSelectedItem().toString()), "Create Model");
                fillBrand();
                fillModel();

            } else {
                mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void createButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton2ActionPerformed
        try {
            if (!this.nameField.getText().isBlank()) {
                mainCont.createWindowMessage(controllerB.create(this.nameField.getText()), "Create Brand");
                fillBrand();
                fillModel();

            } else {
                mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_createButton2ActionPerformed

    private void comboBrandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBrandItemStateChanged

        fillModel();
    }//GEN-LAST:event_comboBrandItemStateChanged

    private void createButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton1ActionPerformed
        try {
            if (this.comboBrand.getSelectedIndex() != -1) {
                mainCont.createWindowMessage(controllerB.deleteT(this.comboBrand.getSelectedItem().toString()), "Delete Brand");
                fillBrand();
                fillModel();

            } else {
                mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createButton1ActionPerformed

    private void deleteModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteModelButtonActionPerformed
             try {
            if (this.comboBrand.getSelectedIndex() != -1) {
                mainCont.createWindowMessage(controllerModelP.deleteT(this.comboModel.getSelectedItem().toString(),this.comboBrand.getSelectedItem().toString()), "Delete Model");
                fillBrand();
                fillModel();

            } else {
                mainCont.createWindowMessage("Missing data", "Blank Fields");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteModelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBrand;
    private javax.swing.JComboBox<String> comboModel;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton createButton;
    private javax.swing.JButton createButton1;
    private javax.swing.JButton createButton2;
    private javax.swing.JButton deleteModelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables
}
