/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.View.adminPanels;

import com.Controllers.Controller_Brand;
import com.Controllers.Controller_Main;
import com.Controllers.Controller_ModelP;
import com.Controllers.Controller_TypeClockxBrand;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author garroakion
 */
public class Model extends javax.swing.JPanel {
    private  Controller_Main mainCont= Controller_Main.getContMain();
    private Controller_Brand controllerB;
    private Controller_TypeClockxBrand contTypeCxBrand;
    private Controller_ModelP controllerModelP;
    /**
     * Creates new form Model
     */
    public Model() {
        initComponents();
        controllerB=mainCont.getContBrand();
        controllerModelP=mainCont.getContModelP();
        contTypeCxBrand=mainCont.getContTypexBrand();
       
    }
    
  
        
         private void fillBrand(){
        try{
            ArrayList<String> listC= controllerB.listInfoCombo();
            DefaultComboBoxModel listF=new DefaultComboBoxModel(listC.toArray());
            this.comboBrand.setModel(listF);
            
        }catch(Exception e){
        System.out.println(e.toString());
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBrand = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        createButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        comboBrand = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        createButton2 = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        modifyButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBrand.setBackground(new java.awt.Color(0, 0, 102));
        titleBrand.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Clock Model");
        jLabel1.setToolTipText("");
        titleBrand.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 50));

        add(titleBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 50));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setText("Brand:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 50));

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableInfo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 630, 290));

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create Model");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 300, 30));

        comboBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 300, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Model name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 50));

        createButton2.setBackground(new java.awt.Color(0, 0, 0));
        createButton2.setForeground(new java.awt.Color(255, 255, 255));
        createButton2.setText("Create Brand");
        createButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton2ActionPerformed(evt);
            }
        });
        add(createButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 30));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 90, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 50));

        modifyButton1.setBackground(new java.awt.Color(0, 0, 0));
        modifyButton1.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton1.setText("Add type to brand");
        add(modifyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
     
    }//GEN-LAST:event_createButtonActionPerformed

    private void createButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton2ActionPerformed
                try{
            if (!this.nameField.getText().isBlank()&&this.comboType.getSelectedItem().toString()!=null){
                mainCont.createWindowMessage(controllerB.create(this.nameField.getText(),this.comboType.getSelectedItem().toString()), "Create Brand");
            fillBrand();

        }
        else {mainCont.createWindowMessage("Missing data", "Blank Fields");
        }
        }
        catch(Exception e){
                System.out.println(e.toString());
        }    
    }//GEN-LAST:event_createButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBrand;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton createButton;
    private javax.swing.JButton createButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyButton1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable tableInfo;
    private javax.swing.JPanel titleBrand;
    // End of variables declaration//GEN-END:variables
}
